name = "soundtrack-comments"
main = "src/worker.js"
compatibility_date = "2026-02-10"

[vars]
ALLOWED_ORIGINS = "https://jlsp124.github.io,http://127.0.0.1:5500"

[[d1_databases]]
binding = "DB"
database_name = "soundtrack-comments"
database_id = "a886b015-c528-4e2f-8cc9-f013c3b5865b"

[[kv_namespaces]]
binding = "SOUNDTRACK_RATE_LIMIT"
id = "dc017571e8c0418fb316238d9eafb68e"